# Model hyperparameters
model:
  # GraphUNet specific args
  hidden_dim: 128
  depth: 3
  pool_ratios: [0.95, 0.95, 0.95]

  # MLP Head args
  activation_mlps_final: "ELU"
  dropout_mlps_final: 0 # default = 0.1, overfit = 0
  hid_mlp_dim: 256

# Training parameters
training:
  lr: 0.001
  epochs: 500
  batch_size: 1 # PyG trajectories are large (T steps), batch_size 1-2 is usually max
  shuffle: False # False for overfitting
  adam_weight_decay: 0
  num_train_trajs: 10
  mode: "overfit" # None or "overfit"
  gamma_lr_scheduler: 0.999
  random_seed: 42
  # Overfit settings
  overfit_traj_id: 0 # Which trajectory index to overfit on
  overfit_time_idx: [0, 1, 2, 3, 4, 5, 6, 7] # specific time steps to train on
  # Paths
  datapath: "processed_data/pyg_data" # Folder containing pyg_processed_data.pt
  model_path_out: "model_out/"
  # Optimization
  amp: False
  move_all_to_device: True # Load entire dataset to GPU memory (Very fast for small/medium datasets)